name: Continous integration

on:
  pull_request:
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest --junitxml=test-results/test-results.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/macos@v2
        if: always()
        with:
          files: test-results/*.xml